service: apollo-lambda
plugins:
  - serverless-offline
Resources:
ItemsTable:
  Type: "AWS::DynamoDB::Table"
  Properties:
    TableName: "trips"
    AttributeDefinitions:
    - AttributeName: "id"
      AttributeType: "N"
    KeySchema:
    - AttributeName: "id"
      KeyType: "HASH"
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5            
DifferentTermsPages:
  Type: "AWS::DynamoDB::Table"
  Properties:             
    TableName: "users"
    AttributeDefinitions:
    - AttributeName: "id"
      AttributeType: "N"
    KeySchema:
    - AttributeName: "id"
      KeyType: "HASH"
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5 
custom:
  serverless-offline:
    httpPort: 4000
provider:
  name: aws
  runtime: nodejs12.x
  dynamodbLocalhost: ${opt:dynamodbLocalhost, ''}
functions:
  graphql:
    handler: src/index.graphqlHandler
    environment:
      DYNAMODB_LOCALHOST: ${self:provider.dynamodbLocalhost}
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true